#ifndef __SEED_NAMES_H__
#define __SEED_NAMES_H__

#define SEED_LT_TMP                                               0
#define SEED_LT_INIT                                              1
#define SEED_LT_FIN                                               399

// Client's logs
#define SEED_LT_CLIENT_BEFORE_TCP_CONNECT                         2
#define SEED_LT_CLIENT_AFTER_TCP_CONNECT                          3
#define SEED_LT_CLIENT_BEFORE_TLS_CONNECT                         4
#define SEED_LT_CLIENT_AFTER_TLS_CONNECT                          5
#define SEED_LT_CLIENT_FETCH_HTML_START                           6
#define SEED_LT_CLIENT_FETCH_HTML_END                             7

// Client only receives HelloRequest
#define SEED_LT_CLIENT_START_HELLO_REQUEST                        8
#define SEED_LT_CLIENT_RECV_HELLO_REQUEST                         9
#define SEED_LT_CLIENT_BEFORE_PROCESS_HELLO_REQUEST               10
#define SEED_LT_CLIENT_AFTER_PROCESS_HELLO_REQUEST                11
#define SEED_LT_CLIENT_BEFORE_POST_HELLO_REQUEST                  12
#define SEED_LT_CLIENT_FINISH_HELLO_REQUEST                       13

// Client only sends ClientHello
#define SEED_LT_CLIENT_START_CLIENT_HELLO                         14
#define SEED_LT_CLIENT_CONSTRUCT_CLIENT_HELLO                     15
#define SEED_LT_CLIENT_BEFORE_SEND_CLIENT_HELLO                   16
#define SEED_LT_CLIENT_AFTER_SEND_CLIENT_HELLO                    17
#define SEED_LT_CLIENT_BEFORE_POST_CLIENT_HELLO                   18
#define SEED_LT_CLIENT_FINISH_CLIENT_HELLO                        19

// Client only receives ServerHello
#define SEED_LT_CLIENT_START_SERVER_HELLO                         20
#define SEED_LT_CLIENT_RECV_SERVER_HELLO                          21
#define SEED_LT_CLIENT_BEFORE_PROCESS_SERVER_HELLO                22
#define SEED_LT_CLIENT_AFTER_PROCESS_SERVER_HELLO                 23
#define SEED_LT_CLIENT_BEFORE_POST_SERVER_HELLO                   24
#define SEED_LT_CLIENT_FINISH_SERVER_HELLO                        25

// Client sends/receives NewSessionTicket
#define SEED_LT_CLIENT_START_WRITE_NEWSESSION_TICKET              26
#define SEED_LT_CLIENT_CONSTRUCT_WRITE_NEWSESSION_TICKET          27
#define SEED_LT_CLIENT_BEFORE_SEND_WRITE_NEWSESSION_TICKET        28
#define SEED_LT_CLIENT_AFTER_SEND_WRITE_NEWSESSION_TICKET         29
#define SEED_LT_CLIENT_BEFORE_POST_WRITE_NEWSESSION_TICKET        30
#define SEED_LT_CLIENT_FINISH_WRITE_NEWSESSION_TICKET             31

#define SEED_LT_CLIENT_START_READ_NEWSESSION_TICKET               32
#define SEED_LT_CLIENT_RECV_READ_NEWSESSION_TICKET                33
#define SEED_LT_CLIENT_BEFORE_PROCESS_READ_NEWSESSION_TICKET      34
#define SEED_LT_CLIENT_AFTER_PROCESS_READ_NEWSESSION_TICKET       35
#define SEED_LT_CLIENT_BEFORE_POST_READ_NEWSESSION_TICKET         36
#define SEED_LT_CLIENT_FINISH_READ_NEWSESSION_TICKET              37

// Client only sends EarlyData
#define SEED_LT_CLIENT_START_END_OF_EARLY_DATA                    38
#define SEED_LT_CLIENT_CONSTRUCT_END_OF_EARLY_DATA                39
#define SEED_LT_CLIENT_BEFORE_SEND_END_OF_EARLY_DATA              40
#define SEED_LT_CLIENT_AFTER_SEND_END_OF_EARLY_DATA               41
#define SEED_LT_CLIENT_BEFORE_POST_END_OF_EARLY_DATA              42
#define SEED_LT_CLIENT_FINISH_END_OF_EARLY_DATA                   43

// Client only receives EncryptedExtensions
#define SEED_LT_CLIENT_START_ENCRYPTED_EXTENSIONS                 44
#define SEED_LT_CLIENT_RECV_ENCRYPTED_EXTENSIONS                  45
#define SEED_LT_CLIENT_BEFORE_PROCESS_ENCRYPTED_EXTENSIONS        46
#define SEED_LT_CLIENT_AFTER_PROCESS_ENCRYPTED_EXTENSIONS         47
#define SEED_LT_CLIENT_BEFORE_POST_ENCRYPTED_EXTENSIONS           48
#define SEED_LT_CLIENT_FINISH_ENCRYPTED_EXTENSIONS                49

// Client sends/receives Certificate
#define SEED_LT_CLIENT_START_WRITE_CERTIFICATE                    50
#define SEED_LT_CLIENT_CONSTRUCT_WRITE_CERTIFICATE                51
#define SEED_LT_CLIENT_BEFORE_SEND_WRITE_CERTIFICATE              52
#define SEED_LT_CLIENT_AFTER_SEND_WRITE_CERTIFICATE               53
#define SEED_LT_CLIENT_BEFORE_POST_WRITE_CERTIFICATE              54
#define SEED_LT_CLIENT_FINISH_WRITE_CERTIFICATE                   55

#define SEED_LT_CLIENT_START_READ_CERTIFICATE                     56
#define SEED_LT_CLIENT_RECV_READ_CERTIFICATE                      57
#define SEED_LT_CLIENT_BEFORE_PROCESS_READ_CERTIFICATE            58
#define SEED_LT_CLIENT_AFTER_PROCESS_READ_CERTIFICATE             59
#define SEED_LT_CLIENT_BEFORE_POST_READ_CERTIFICATE               60
#define SEED_LT_CLIENT_FINISH_READ_CERTIFICATE                    61

// Client only receives ServerKeyExchange
#define SEED_LT_CLIENT_START_SERVER_KEY_EXCHANGE                  62
#define SEED_LT_CLIENT_RECV_SERVER_KEY_EXCHANGE                   63
#define SEED_LT_CLIENT_BEFORE_PROCESS_SERVER_KEY_EXCHANGE         64
#define SEED_LT_CLIENT_AFTER_PROCESS_SERVER_KEY_EXCHANGE          65
#define SEED_LT_CLIENT_BEFORE_POST_SERVER_KEY_EXCHANGE            66
#define SEED_LT_CLIENT_FINISH_SERVER_KEY_EXCHANGE                 67

// Client only receives CertificateRequest
#define SEED_LT_CLIENT_START_CERTIFICATE_REQUEST                  68
#define SEED_LT_CLIENT_RECV_CERTIFICATE_REQUEST                   69
#define SEED_LT_CLIENT_BEFORE_PROCESS_CERTIFICATE_REQUEST         70
#define SEED_LT_CLIENT_AFTER_PROCESS_CERTIFICATE_REQUEST          71
#define SEED_LT_CLIENT_BEFORE_POST_CERTIFICATE_REQUEST            72
#define SEED_LT_CLIENT_FINISH_CERTIFICATE_REQUEST                 73

// Client only receives ServerDone
#define SEED_LT_CLIENT_START_SERVER_DONE                          74
#define SEED_LT_CLIENT_RECV_SERVER_DONE                           75
#define SEED_LT_CLIENT_BEFORE_PROCESS_SERVER_DONE                 76
#define SEED_LT_CLIENT_AFTER_PROCESS_SERVER_DONE                  77
#define SEED_LT_CLIENT_BEFORE_POST_SERVER_DONE                    78
#define SEED_LT_CLIENT_FINISH_SERVER_DONE                         79

// Client sends/receives CertificateVerify
#define SEED_LT_CLIENT_START_WRITE_CERTIFICATE_VERIFY             80
#define SEED_LT_CLIENT_CONSTRUCT_WRITE_CERTIFICATE_VERIFY         81
#define SEED_LT_CLIENT_BEFORE_SEND_WRITE_CERTIFICATE_VERIFY       82
#define SEED_LT_CLIENT_AFTER_SEND_WRITE_CERTIFICATE_VERIFY        83
#define SEED_LT_CLIENT_BEFORE_POST_WRITE_CERTIFICATE_VERIFY       84
#define SEED_LT_CLIENT_FINISH_WRITE_CERTIFICATE_VERIFY            85

#define SEED_LT_CLIENT_START_READ_CERTIFICATE_VERIFY              86
#define SEED_LT_CLIENT_RECV_READ_CERTIFICATE_VERIFY               87
#define SEED_LT_CLIENT_BEFORE_PROCESS_READ_CERTIFICATE_VERIFY     88
#define SEED_LT_CLIENT_AFTER_PROCESS_READ_CERTIFICATE_VERIFY      89
#define SEED_LT_CLIENT_BEFORE_POST_READ_CERTIFICATE_VERIFY        90
#define SEED_LT_CLIENT_FINISH_READ_CERTIFICATE_VERIFY             91

// Client only sends ClientKeyExchange
#define SEED_LT_CLIENT_START_CLIENT_KEY_EXCHANGE                  92
#define SEED_LT_CLIENT_CONSTRUCT_CLIENT_KEY_EXCHANGE              93
#define SEED_LT_CLIENT_BEFORE_SEND_CLIENT_KEY_EXCHANGE            94
#define SEED_LT_CLIENT_AFTER_SEND_CLIENT_KEY_EXCHANGE             95
#define SEED_LT_CLIENT_BEFORE_POST_CLIENT_KEY_EXCHANGE            96
#define SEED_LT_CLIENT_FINISH_CLIENT_KEY_EXCHANGE                 97

// Client only sends ClientFinished
#define SEED_LT_CLIENT_START_CLIENT_FINISHED                      98
#define SEED_LT_CLIENT_CONSTRUCT_CLIENT_FINISHED                  99
#define SEED_LT_CLIENT_BEFORE_SEND_CLIENT_FINISHED                100
#define SEED_LT_CLIENT_AFTER_SEND_CLIENT_FINISHED                 101
#define SEED_LT_CLIENT_BEFORE_POST_CLIENT_FINISHED                102
#define SEED_LT_CLIENT_FINISH_CLIENT_FINISHED                     103

// Client only receives ServerFinished
#define SEED_LT_CLIENT_START_SERVER_FINISHED                      104
#define SEED_LT_CLIENT_RECV_SERVER_FINISHED                       105
#define SEED_LT_CLIENT_BEFORE_PROCESS_SERVER_FINISHED             106
#define SEED_LT_CLIENT_AFTER_PROCESS_SERVER_FINISHED              107
#define SEED_LT_CLIENT_BEFORE_POST_SERVER_FINISHED                108
#define SEED_LT_CLIENT_FINISH_SERVER_FINISHED                     109

// Client only receives CertificateURL
#define SEED_LT_CLIENT_START_CERTIFICATE_URL                      110
#define SEED_LT_CLIENT_RECV_CERTIFICATE_URL                       111
#define SEED_LT_CLIENT_BEFORE_PROCESS_CERTIFICATE_URL             112
#define SEED_LT_CLIENT_AFTER_PROCESS_CERTIFICATE_URL              113
#define SEED_LT_CLIENT_BEFORE_POST_CERTIFICATE_URL                114
#define SEED_LT_CLIENT_FINISH_CERTIFICATE_URL                     115

// Client only receives CertificateStatus
#define SEED_LT_CLIENT_START_CERTIFICATE_STATUS                   116
#define SEED_LT_CLIENT_RECV_CERTIFICATE_STATUS                    117
#define SEED_LT_CLIENT_BEFORE_PROCESS_CERTIFICATE_STATUS          118
#define SEED_LT_CLIENT_AFTER_PROCESS_CERTIFICATE_STATUS           119
#define SEED_LT_CLIENT_BEFORE_POST_CERTIFICATE_STATUS             120
#define SEED_LT_CLIENT_FINISH_CERTIFICATE_STATUS                  121

// Client sends/receives SupplementalData
#define SEED_LT_CLIENT_START_WRITE_SUPPLEMENTAL_DATA              122
#define SEED_LT_CLIENT_CONSTRUCT_WRITE_SUPPLEMENTAL_DATA          123
#define SEED_LT_CLIENT_BEFORE_SEND_WRITE_SUPPLEMENTAL_DATA        124
#define SEED_LT_CLIENT_AFTER_SEND_WRITE_SUPPLEMENTAL_DATA         125
#define SEED_LT_CLIENT_BEFORE_POST_WRITE_SUPPLEMENTAL_DATA        126
#define SEED_LT_CLIENT_FINISH_WRITE_SUPPLEMENTAL_DATA             127

#define SEED_LT_CLIENT_START_READ_SUPPLEMENTAL_DATA               128
#define SEED_LT_CLIENT_RECV_READ_SUPPLEMENTAL_DATA                129
#define SEED_LT_CLIENT_BEFORE_PROCESS_READ_SUPPLEMENTAL_DATA      130
#define SEED_LT_CLIENT_AFTER_PROCESS_READ_SUPPLEMENTAL_DATA       131
#define SEED_LT_CLIENT_BEFORE_POST_READ_SUPPLEMENTAL_DATA         132
#define SEED_LT_CLIENT_FINISH_READ_SUPPLEMENTAL_DATA              133

// Client sends/receives KeyUpdate
#define SEED_LT_CLIENT_START_WRITE_KEY_UPDATE                     134
#define SEED_LT_CLIENT_CONSTRUCT_WRITE_KEY_UPDATE                 135
#define SEED_LT_CLIENT_BEFORE_SEND_WRITE_KEY_UPDATE               136
#define SEED_LT_CLIENT_AFTER_SEND_WRITE_KEY_UPDATE                137
#define SEED_LT_CLIENT_BEFORE_POST_WRITE_KEY_UPDATE               138
#define SEED_LT_CLIENT_FINISH_WRITE_KEY_UPDATE                    139

#define SEED_LT_CLIENT_START_READ_KEY_UPDATE                      140
#define SEED_LT_CLIENT_RECV_READ_KEY_UPDATE                       141
#define SEED_LT_CLIENT_BEFORE_PROCESS_READ_KEY_UPDATE             142
#define SEED_LT_CLIENT_AFTER_PROCESS_READ_KEY_UPDATE              143
#define SEED_LT_CLIENT_BEFORE_POST_READ_KEY_UPDATE                144
#define SEED_LT_CLIENT_FINISH_READ_KEY_UPDATE                     145

// Client sends/receives MessageHash
#define SEED_LT_CLIENT_START_WRITE_MESSAGE_HASH                   146
#define SEED_LT_CLIENT_CONSTRUCT_WRITE_MESSAGE_HASH               147
#define SEED_LT_CLIENT_BEFORE_SEND_WRITE_MESSAGE_HASH             148
#define SEED_LT_CLIENT_AFTER_SEND_WRITE_MESSAGE_HASH              149
#define SEED_LT_CLIENT_BEFORE_POST_WRITE_MESSAGE_HASH             150
#define SEED_LT_CLIENT_FINISH_WRITE_MESSAGE_HASH                  151

#define SEED_LT_CLIENT_START_READ_MESSAGE_HASH                    152
#define SEED_LT_CLIENT_RECV_READ_MESSAGE_HASH                     153
#define SEED_LT_CLIENT_BEFORE_PROCESS_READ_MESSAGE_HASH           154
#define SEED_LT_CLIENT_AFTER_PROCESS_READ_MESSAGE_HASH            155
#define SEED_LT_CLIENT_BEFORE_POST_READ_MESSAGE_HASH              156
#define SEED_LT_CLIENT_FINISH_READ_MESSAGE_HASH                   157

// Client sends/receives ChangeCipherSpec
#define SEED_LT_CLIENT_START_WRITE_CHANGE_CIPHER_SPEC             158
#define SEED_LT_CLIENT_CONSTRUCT_WRITE_CHANGE_CIPHER_SPEC         159
#define SEED_LT_CLIENT_BEFORE_SEND_WRITE_CHANGE_CIPHER_SPEC       160
#define SEED_LT_CLIENT_AFTER_SEND_WRITE_CHANGE_CIPHER_SPEC        161
#define SEED_LT_CLIENT_BEFORE_POST_WRITE_CHANGE_CIPHER_SPEC       162
#define SEED_LT_CLIENT_FINISH_WRITE_CHANGE_CIPHER_SPEC            163

#define SEED_LT_CLIENT_START_READ_CHANGE_CIPHER_SPEC              164
#define SEED_LT_CLIENT_RECV_READ_CHANGE_CIPHER_SPEC               165
#define SEED_LT_CLIENT_BEFORE_PROCESS_READ_CHANGE_CIPHER_SPEC     166
#define SEED_LT_CLIENT_AFTER_PROCESS_READ_CHANGE_CIPHER_SPEC      167
#define SEED_LT_CLIENT_BEFORE_POST_READ_CHANGE_CIPHER_SPEC        168
#define SEED_LT_CLIENT_FINISH_READ_CHANGE_CIPHER_SPEC             169

// Temporary Variables for Client
#define SEED_LT_CLIENT_TMP_0                                      170
#define SEED_LT_CLIENT_TMP_1                                      171
#define SEED_LT_CLIENT_TMP_2                                      172
#define SEED_LT_CLIENT_TMP_3                                      173


/* Server's log */
#define SEED_LT_SERVER_BEFORE_TCP_ACCEPT                          202
#define SEED_LT_SERVER_AFTER_TCP_ACCEPT                           203
#define SEED_LT_SERVER_BEFORE_TLS_ACCEPT                          204
#define SEED_LT_SERVER_AFTER_TLS_ACCEPT                           205
#define SEED_LT_SERVER_SERVE_HTML_START                           206
#define SEED_LT_SERVER_SERVE_HTML_END                             207

// Server only sends HelloRequest
#define SEED_LT_SERVER_START_HELLO_REQUEST                        208
#define SEED_LT_SERVER_CONSTRUCT_HELLO_REQUEST                    209
#define SEED_LT_SERVER_BEFORE_SEND_HELLO_REQUEST                  210
#define SEED_LT_SERVER_AFTER_SEND_HELLO_REQUEST                   211
#define SEED_LT_SERVER_BEFORE_POST_HELLO_REQUEST                  212
#define SEED_LT_SERVER_FINISH_HELLO_REQUEST                       213

// Server only receives ClientHello
#define SEED_LT_SERVER_START_CLIENT_HELLO                         214
#define SEED_LT_SERVER_RECV_CLIENT_HELLO                          215
#define SEED_LT_SERVER_BEFORE_PROCESS_CLIENT_HELLO                216
#define SEED_LT_SERVER_AFTER_PROCESS_CLIENT_HELLO                 217
#define SEED_LT_SERVER_BEFORE_POST_CLIENT_HELLO                   218
#define SEED_LT_SERVER_FINISH_CLIENT_HELLO                        219

// Server only sends ServerHello
#define SEED_LT_SERVER_START_SERVER_HELLO                         220
#define SEED_LT_SERVER_CONSTRUCT_SERVER_HELLO                     221
#define SEED_LT_SERVER_BEFORE_SEND_SERVER_HELLO                   222
#define SEED_LT_SERVER_AFTER_SEND_SERVER_HELLO                    223
#define SEED_LT_SERVER_BEFORE_POST_SERVER_HELLO                   224
#define SEED_LT_SERVER_FINISH_SERVER_HELLO                        225

// Server sends/receives NewSessionTicket
#define SEED_LT_SERVER_START_READ_NEWSESSION_TICKET               226
#define SEED_LT_SERVER_RECV_READ_NEWSESSION_TICKET                227
#define SEED_LT_SERVER_BEFORE_PROCESS_READ_NEWSESSION_TICKET      228
#define SEED_LT_SERVER_AFTER_PROCESS_READ_NEWSESSION_TICKET       229
#define SEED_LT_SERVER_BEFORE_POST_READ_NEWSESSION_TICKET         230
#define SEED_LT_SERVER_FINISH_READ_NEWSESSION_TICKET              231

#define SEED_LT_SERVER_START_WRITE_NEWSESSION_TICKET              232
#define SEED_LT_SERVER_CONSTRUCT_WRITE_NEWSESSION_TICKET          233
#define SEED_LT_SERVER_BEFORE_SEND_WRITE_NEWSESSION_TICKET        234
#define SEED_LT_SERVER_AFTER_SEND_WRITE_NEWSESSION_TICKET         235
#define SEED_LT_SERVER_BEFORE_POST_WRITE_NEWSESSION_TICKET        236
#define SEED_LT_SERVER_FINISH_WRITE_NEWSESSION_TICKET             237

// Server only receives EarlyData
#define SEED_LT_SERVER_START_END_OF_EARLY_DATA                    238
#define SEED_LT_SERVER_RECV_END_OF_EARLY_DATA                     239
#define SEED_LT_SERVER_BEFORE_PROCESS_END_OF_EARLY_DATA           240
#define SEED_LT_SERVER_AFTER_PROCESS_END_OF_EARLY_DATA            241
#define SEED_LT_SERVER_BEFORE_POST_END_OF_EARLY_DATA              242
#define SEED_LT_SERVER_FINISH_END_OF_EARLY_DATA                   243

// Server only sends EncryptedExtensions
#define SEED_LT_SERVER_START_ENCRYPTED_EXTENSIONS                 244
#define SEED_LT_SERVER_CONSTRUCT_ENCRYPTED_EXTENSIONS             245
#define SEED_LT_SERVER_BEFORE_SEND_ENCRYPTED_EXTENSIONS           246
#define SEED_LT_SERVER_AFTER_SEND_ENCRYPTED_EXTENSIONS            247
#define SEED_LT_SERVER_BEFORE_POST_ENCRYPTED_EXTENSIONS           248
#define SEED_LT_SERVER_FINISH_ENCRYPTED_EXTENSIONS                249

// Server sends/receives Certificate
#define SEED_LT_SERVER_START_READ_CERTIFICATE                     250
#define SEED_LT_SERVER_RECV_READ_CERTIFICATE                      251
#define SEED_LT_SERVER_BEFORE_PROCESS_READ_CERTIFICATE            252
#define SEED_LT_SERVER_AFTER_PROCESS_READ_CERTIFICATE             253
#define SEED_LT_SERVER_BEFORE_POST_READ_CERTIFICATE               254
#define SEED_LT_SERVER_FINISH_READ_CERTIFICATE                    255

#define SEED_LT_SERVER_START_WRITE_CERTIFICATE                    256
#define SEED_LT_SERVER_CONSTRUCT_WRITE_CERTIFICATE                257
#define SEED_LT_SERVER_BEFORE_SEND_WRITE_CERTIFICATE              258
#define SEED_LT_SERVER_AFTER_SEND_WRITE_CERTIFICATE               259
#define SEED_LT_SERVER_BEFORE_POST_WRITE_CERTIFICATE              260
#define SEED_LT_SERVER_FINISH_WRITE_CERTIFICATE                   261

// Server only sends ServerKeyExchange
#define SEED_LT_SERVER_START_SERVER_KEY_EXCHANGE                  262
#define SEED_LT_SERVER_CONSTRUCT_SERVER_KEY_EXCHANGE              263
#define SEED_LT_SERVER_BEFORE_SEND_SERVER_KEY_EXCHANGE            264
#define SEED_LT_SERVER_AFTER_SEND_SERVER_KEY_EXCHANGE             265
#define SEED_LT_SERVER_BEFORE_POST_SERVER_KEY_EXCHANGE            266
#define SEED_LT_SERVER_FINISH_SERVER_KEY_EXCHANGE                 267

// Server only sends CertificateRequest
#define SEED_LT_SERVER_START_CERTIFICATE_REQUEST                  268
#define SEED_LT_SERVER_CONSTRUCT_CERTIFICATE_REQUEST              269
#define SEED_LT_SERVER_BEFORE_SEND_CERTIFICATE_REQUEST            270
#define SEED_LT_SERVER_AFTER_SEND_CERTIFICATE_REQUEST             271
#define SEED_LT_SERVER_BEFORE_POST_CERTIFICATE_REQUEST            272
#define SEED_LT_SERVER_FINISH_CERTIFICATE_REQUEST                 273

// Server only sends ServerDone
#define SEED_LT_SERVER_START_SERVER_DONE                          274
#define SEED_LT_SERVER_CONSTRUCT_SERVER_DONE                      275
#define SEED_LT_SERVER_BEFORE_SEND_SERVER_DONE                    276
#define SEED_LT_SERVER_AFTER_SEND_SERVER_DONE                     277
#define SEED_LT_SERVER_BEFORE_POST_SERVER_DONE                    278
#define SEED_LT_SERVER_FINISH_SERVER_DONE                         279

// Server sends/receives CertificateVerify
#define SEED_LT_SERVER_START_READ_CERTIFICATE_VERIFY              280
#define SEED_LT_SERVER_RECV_READ_CERTIFICATE_VERIFY               281
#define SEED_LT_SERVER_BEFORE_PROCESS_READ_CERTIFICATE_VERIFY     282
#define SEED_LT_SERVER_AFTER_PROCESS_READ_CERTIFICATE_VERIFY      283
#define SEED_LT_SERVER_BEFORE_POST_READ_CERTIFICATE_VERIFY        284
#define SEED_LT_SERVER_FINISH_READ_CERTIFICATE_VERIFY             285

#define SEED_LT_SERVER_START_WRITE_CERTIFICATE_VERIFY             286
#define SEED_LT_SERVER_CONSTRUCT_WRITE_CERTIFICATE_VERIFY         287
#define SEED_LT_SERVER_BEFORE_SEND_WRITE_CERTIFICATE_VERIFY       288
#define SEED_LT_SERVER_AFTER_SEND_WRITE_CERTIFICATE_VERIFY        289
#define SEED_LT_SERVER_BEFORE_POST_WRITE_CERTIFICATE_VERIFY       290
#define SEED_LT_SERVER_FINISH_WRITE_CERTIFICATE_VERIFY            291

// Server only receives ClientKeyExchange
#define SEED_LT_SERVER_START_CLIENT_KEY_EXCHANGE                  292
#define SEED_LT_SERVER_RECV_CLIENT_KEY_EXCHANGE                   293
#define SEED_LT_SERVER_BEFORE_PROCESS_CLIENT_KEY_EXCHANGE         294
#define SEED_LT_SERVER_AFTER_PROCESS_CLIENT_KEY_EXCHANGE          295
#define SEED_LT_SERVER_BEFORE_POST_CLIENT_KEY_EXCHANGE            296
#define SEED_LT_SERVER_FINISH_CLIENT_KEY_EXCHANGE                 297

// Server only receives ClientFinished
#define SEED_LT_SERVER_START_CLIENT_FINISHED                      298
#define SEED_LT_SERVER_RECV_CLIENT_FINISHED                       299
#define SEED_LT_SERVER_BEFORE_PROCESS_CLIENT_FINISHED             300
#define SEED_LT_SERVER_AFTER_PROCESS_CLIENT_FINISHED              301
#define SEED_LT_SERVER_BEFORE_POST_CLIENT_FINISHED                302
#define SEED_LT_SERVER_FINISH_CLIENT_FINISHED                     303

// Server only sends ServerFinished
#define SEED_LT_SERVER_START_SERVER_FINISHED                      304
#define SEED_LT_SERVER_CONSTRUCT_SERVER_FINISHED                  305
#define SEED_LT_SERVER_BEFORE_SEND_SERVER_FINISHED                306
#define SEED_LT_SERVER_AFTER_SEND_SERVER_FINISHED                 307
#define SEED_LT_SERVER_BEFORE_POST_SERVER_FINISHED                308
#define SEED_LT_SERVER_FINISH_SERVER_FINISHED                     309

// Server only sends CertificateURL
#define SEED_LT_SERVER_START_CERTIFICATE_URL                      310
#define SEED_LT_SERVER_CONSTRUCT_CERTIFICATE_URL                  311
#define SEED_LT_SERVER_BEFORE_SEND_CERTIFICATE_URL                312
#define SEED_LT_SERVER_AFTER_SEND_CERTIFICATE_URL                 313
#define SEED_LT_SERVER_BEFORE_POST_CERTIFICATE_URL                314
#define SEED_LT_SERVER_FINISH_CERTIFICATE_URL                     315

// Server only sends CertificateStatus
#define SEED_LT_SERVER_START_CERTIFICATE_STATUS                   316
#define SEED_LT_SERVER_CONSTRUCT_CERTIFICATE_STATUS               317
#define SEED_LT_SERVER_BEFORE_SEND_CERTIFICATE_STATUS             318
#define SEED_LT_SERVER_AFTER_SEND_CERTIFICATE_STATUS              319
#define SEED_LT_SERVER_BEFORE_POST_CERTIFICATE_STATUS             320
#define SEED_LT_SERVER_FINISH_CERTIFICATE_STATUS                  321

// Server sends/receives SupplementalData
#define SEED_LT_SERVER_START_WRITE_SUPPLEMENTAL_DATA              322
#define SEED_LT_SERVER_CONSTRUCT_WRITE_SUPPLEMENTAL_DATA          323
#define SEED_LT_SERVER_BEFORE_SEND_WRITE_SUPPLEMENTAL_DATA        324
#define SEED_LT_SERVER_AFTER_SEND_WRITE_SUPPLEMENTAL_DATA         325
#define SEED_LT_SERVER_BEFORE_POST_WRITE_SUPPLEMENTAL_DATA        326
#define SEED_LT_SERVER_FINISH_WRITE_SUPPLEMENTAL_DATA             327

#define SEED_LT_SERVER_START_READ_SUPPLEMENTAL_DATA               328
#define SEED_LT_SERVER_RECV_READ_SUPPLEMENTAL_DATA                329
#define SEED_LT_SERVER_BEFORE_PROCESS_READ_SUPPLEMENTAL_DATA      330
#define SEED_LT_SERVER_AFTER_PROCESS_READ_SUPPLEMENTAL_DATA       331
#define SEED_LT_SERVER_BEFORE_POST_READ_SUPPLEMENTAL_DATA         332
#define SEED_LT_SERVER_FINISH_READ_SUPPLEMENTAL_DATA              333

// Server sends/receives KeyUpdate
#define SEED_LT_SERVER_START_WRITE_KEY_UPDATE                     334
#define SEED_LT_SERVER_CONSTRUCT_WRITE_KEY_UPDATE                 335
#define SEED_LT_SERVER_BEFORE_SEND_WRITE_KEY_UPDATE               336
#define SEED_LT_SERVER_AFTER_SEND_WRITE_KEY_UPDATE                337
#define SEED_LT_SERVER_BEFORE_POST_WRITE_KEY_UPDATE               338
#define SEED_LT_SERVER_FINISH_WRITE_KEY_UPDATE                    339

#define SEED_LT_SERVER_START_READ_KEY_UPDATE                      340
#define SEED_LT_SERVER_RECV_READ_KEY_UPDATE                       341
#define SEED_LT_SERVER_BEFORE_PROCESS_READ_KEY_UPDATE             342
#define SEED_LT_SERVER_AFTER_PROCESS_READ_KEY_UPDATE              343
#define SEED_LT_SERVER_BEFORE_POST_READ_KEY_UPDATE                344
#define SEED_LT_SERVER_FINISH_READ_KEY_UPDATE                     345

// Server sends/receives MessageHash
#define SEED_LT_SERVER_START_WRITE_MESSAGE_HASH                   346
#define SEED_LT_SERVER_CONSTRUCT_WRITE_MESSAGE_HASH               347
#define SEED_LT_SERVER_BEFORE_SEND_WRITE_MESSAGE_HASH             348
#define SEED_LT_SERVER_AFTER_SEND_WRITE_MESSAGE_HASH              349
#define SEED_LT_SERVER_BEFORE_POST_WRITE_MESSAGE_HASH             350
#define SEED_LT_SERVER_FINISH_WRITE_MESSAGE_HASH                  351

#define SEED_LT_SERVER_START_READ_MESSAGE_HASH                    352
#define SEED_LT_SERVER_RECV_READ_MESSAGE_HASH                     353
#define SEED_LT_SERVER_BEFORE_PROCESS_READ_MESSAGE_HASH           354
#define SEED_LT_SERVER_AFTER_PROCESS_READ_MESSAGE_HASH            355
#define SEED_LT_SERVER_BEFORE_POST_READ_MESSAGE_HASH              356
#define SEED_LT_SERVER_FINISH_READ_MESSAGE_HASH                   357

// Server sends/receives ChangeCipherSpec
#define SEED_LT_SERVER_START_WRITE_CHANGE_CIPHER_SPEC             358
#define SEED_LT_SERVER_CONSTRUCT_WRITE_CHANGE_CIPHER_SPEC         359
#define SEED_LT_SERVER_BEFORE_SEND_WRITE_CHANGE_CIPHER_SPEC       360
#define SEED_LT_SERVER_AFTER_SEND_WRITE_CHANGE_CIPHER_SPEC        361
#define SEED_LT_SERVER_BEFORE_POST_WRITE_CHANGE_CIPHER_SPEC       362
#define SEED_LT_SERVER_FINISH_WRITE_CHANGE_CIPHER_SPEC            363

#define SEED_LT_SERVER_START_READ_CHANGE_CIPHER_SPEC              364
#define SEED_LT_SERVER_RECV_READ_CHANGE_CIPHER_SPEC               365
#define SEED_LT_SERVER_BEFORE_PROCESS_READ_CHANGE_CIPHER_SPEC     366
#define SEED_LT_SERVER_AFTER_PROCESS_READ_CHANGE_CIPHER_SPEC      367
#define SEED_LT_SERVER_BEFORE_POST_READ_CHANGE_CIPHER_SPEC        368
#define SEED_LT_SERVER_FINISH_READ_CHANGE_CIPHER_SPEC             369

#define SEED_LT_SERVER_TMP_0                                      370
#define SEED_LT_SERVER_TMP_1                                      371
#define SEED_LT_SERVER_TMP_2                                      372
#define SEED_LT_SERVER_TMP_3                                      373
#define SEED_LT_SERVER_TMP_4                                      374

#endif /* __SEED_NAMES_H__ */
